[options]
num_models = 1
time_limit = 60
threads = 4

[constraints]
hard = [
    { name = "no_split_double" },
    { name = "minimum_spacing" },
    { name = "no_friday_afternoon" },
    { name = "no_obligatory_conflicts" },
    { name = "no_same_day" },
]

soft = [
    {name = 'maximum_spacing', weight = 3, priority = 2},
    {name = 'no_curriculum_conflicts', weight = 3, priority = 2},
    {name = 'no_different_parts_of_day', weight = 2, priority = 2},
    {name = 'early_classes', weight = 1, priority = 2},
    {name = 'science_and_statistics', weight = 1, priority = 2},
    {name = 'teacher_preferences', weight = 1, priority = 1},
    {name = 'avoid_all_conflicts', weight = 1 , priority = 0},
]
