[clingo]
num_models = 1
time_limit = -1
threads = 4

[constraints]
hard = [
    { name = "double" },
    { name = "no_friday_afternoon" },
    { name = "no_obligatory_conflicts" },
    { name = "no_same_day" },
]

soft = [
    {name = 'teacher_preferences', weight = 1, priority = 1},
    {name = 'avoid_all_conflicts', weight = 1 , priority = 0},
]
