[clingo]
num_models = 1
time_limit = 5
threads = 4

[constraints]
hard = [
    { name = "double" },
    { name = "no_friday_afternoon" },
    { name = "no_obligatory_conflicts" },
    { name = "no_same_day" },
]

soft = [
    {name = 'bounded_spacing', weight = 2, priority = 2},
    {name = 'no_different_periods', weight = 1, priority = 2},
    {name = 'teacher_preferences', weight = 1, priority = 1},
    {name = 'avoid_all_conflicts', weight = 1 , priority = 0},
]
