name: CI

on:
  push:
    branches:
      - main
    paths:
      - "src/py/"
      - "src/asp/"
      - "tests/"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    name: Python ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap python ${{ matrix.python-version }}
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m poetry install

      - name: Run tests (formatting & unit tests)
        run: ./dev/test.sh

